// <auto-generated />
using System;
using MeDirectAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeDirectTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230509214303_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeDirectTest.Models.TransactionModel", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrClientId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrFirstName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("TrFromAmount")
                        .HasMaxLength(300)
                        .HasColumnType("float");

                    b.Property<string>("TrFromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("TrLastName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("TrRate")
                        .HasMaxLength(300)
                        .HasColumnType("float");

                    b.Property<DateTime>("TrRateTimestamp")
                        .HasMaxLength(300)
                        .HasColumnType("datetime2");

                    b.Property<double>("TrResult")
                        .HasMaxLength(300)
                        .HasColumnType("float");

                    b.Property<string>("TrToCurrency")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("TransactionTimestamp")
                        .HasMaxLength(300)
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("TransactionContext");
                });

            modelBuilder.Entity("MeDirectTest.Models.UserModel", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ClientId");

                    b.ToTable("UserContext");
                });
#pragma warning restore 612, 618
        }
    }
}
